eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: order_service_admin
    password: order_service_password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
