eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0
spring:
    application:
        name: product-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            authentication-database: admin
            username: product_service_admin
            password: product_service_password
            database: products